# ====== 1. 빌드 단계 (Gradle 사용) ======
FROM gradle:8.5-jdk17 AS builder

# 필요한 빌드 인자 선언
ARG SPRING_PROFILES_ACTIVE
ARG DATASOURCE_URL_LOCAL
ARG DATASOURCE_USERNAME_LOCAL
ARG DATASOURCE_PASSWORD_LOCAL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_REDIRECT_URI
ARG JWT_ACCESS_EXPIRED_IN
ARG JWT_REFRESH_EXPIRED_IN
ARG JWT_SECRET_KEY
ARG KAKAO_CLIENT_ID
ARG KAKAO_CLIENT_SECRET
ARG NAVER_CLIENT_ID
ARG NAVER_CLIENT_SECRET
ARG BASE_URL

# 빌드 인자들을 환경 변수로 설정 (Gradle이 읽을 수 있도록)
ENV SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
ENV DATASOURCE_URL_LOCAL=${DATASOURCE_URL_LOCAL}
ENV DATASOURCE_USERNAME_LOCAL=${DATASOURCE_USERNAME_LOCAL}
ENV DATASOURCE_PASSWORD_LOCAL=${DATASOURCE_PASSWORD_LOCAL}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
ENV JWT_ACCESS_EXPIRED_IN=${JWT_ACCESS_EXPIRED_IN}
ENV JWT_REFRESH_EXPIRED_IN=${JWT_REFRESH_EXPIRED_IN}
ENV JWT_SECRET_KEY=${JWT_SECRET_KEY}
ENV KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
ENV KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
ENV NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
ENV NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
ENV BASE_URL=${BASE_URL}

# 디버깅을 위한 환경 변수 출력
RUN echo "✅ ENV 확인 START" && \
    echo "SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}" && \
    echo "DATASOURCE_URL_LOCAL=${DATASOURCE_URL_LOCAL}" && \
    echo "DATASOURCE_USERNAME_LOCAL=${DATASOURCE_USERNAME_LOCAL}" && \
    echo "DATASOURCE_PASSWORD_LOCAL=${DATASOURCE_PASSWORD_LOCAL}" && \
    echo "GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}" && \
    echo "GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}" && \
    echo "GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}" && \
    echo "JWT_ACCESS_EXPIRED_IN=${JWT_ACCESS_EXPIRED_IN}" && \
    echo "JWT_REFRESH_EXPIRED_IN=${JWT_REFRESH_EXPIRED_IN}" && \
    echo "JWT_SECRET_KEY=${JWT_SECRET_KEY}" && \
    echo "KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}" && \
    echo "KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}" && \
    echo "NAVER_CLIENT_ID=${NAVER_CLIENT_ID}" && \
    echo "NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}" && \
    echo "BASE_URL=${BASE_URL}" && \
    echo "✅ ENV 확인 END"

# 작업 디렉터리 설정
WORKDIR /app

# 프로젝트 파일 복사
COPY --chown=gradle:gradle . .

# 의존성 미리 다운로드 (캐시 최적화)
RUN gradle dependencies --no-daemon

# Spring Boot 애플리케이션 빌드 (JAR 생성)
RUN gradle bootJar --no-daemon

# ====== 2. 실행 단계 ======
FROM openjdk:17-jdk-slim

# 작업 디렉터리 설정
WORKDIR /app

# 빌드된 JAR 파일 복사
COPY --from=builder /app/build/libs/*.jar app.jar

# 환경 변수 설정 (실행 시 적용)
ENV SPRING_PROFILES_ACTIVE=local

# 컨테이너 실행 시 명령어
CMD ["java", "-jar", "app.jar"]
