# 기본 설정
spring:
  application:
    name: mybeauty
  profiles:
    active: local
    group:
      local: local, secret
      prod: prod, secret
      test: test, secret
    include: secret

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  data:
    redis:
      repositories:
        enabled: false
    jpa:
      repositories:
        bootstrap-mode: default

  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

logging:
  level:
    org:
      hibernate:
        sql: debug
        type.descriptor.sql: trace

      springframework:
        security: DEBUG
        security.oauth2: DEBUG
        web: DEBUG


# aws s3 설정 추가 예정

# Spring Docs 설정 <- Spring Rest Docs 사용할 것인지 Open API를 용한 Swagger 사용할 것인지 고민 후 추가 필요