spring:
  config:
    activate:
      on-profile: local

  sql:
    init:
      platform: mysql
      mode: always

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: none

app:
  baseUrl: http://localhost:8080